Kotlin. Homework #2. Task #1
ArtyomKopan/shallowSizeTemplate pull request #1
Opened 2022-03-28 09:44 UTC by ArtyomKopan

2022-03-28 09:58 UTC, ArtyomKopan commented
CI не может запустить detekt, пишет, что в проекте нет такой задачи gradle. Я посмотрел - и правда, в idea тоже не отображается.
Как можно её туда добавить?

2022-03-31 17:22 UTC, illided requested changes

2022-03-31 17:22 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +        this.isBoolean() || this.isUnit() -> 1
Давай тоже вынесем в константу

2022-03-31 17:22 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                        | fun shallowSize(): Int = TODO()
Хочется какую нибудь полезную ошибку в случае чего получить)

2022-03-31 17:22 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    val sizeFunction = clazz.functions.find { it.name.toString() == "shallowSize" }
Здесь также стоит проверять что нет `valueParameters`

2022-03-31 17:22 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                            +irReturn(irInt(clazz.properties.map { it.backingField?.type?.byteSize() ?: 0 }.sum()))
Давай логику подсчета суммы куда-нибудь вынесем

2022-03-31 17:22 UTC, illided commented on .github/workflows/main.yaml
> +        run: ./gradlew detekt
Сори но меня попросили докапываться до стоковых CI и детект конфигов :(
Давай сюда добавим что нибудь классное, например [тест репорты](https://github.com/actions/upload-artifact)

2022-04-06 17:24 UTC, illided commented
Старайся всегда давать осмысленные названия к комитам, даже если сами коммиты не особо осмысленные)
![Screenshot from 2022-04-06 20-23-01](https://user-images.githubusercontent.com/50303726/162032470-d13a6585-1137-4d1e-99bd-4906a57a5cea.png)

2022-04-06 17:27 UTC, illided requested changes
Сейчас уже намного лучше. Кидай следующий ревиев на Настю

2022-04-06 17:27 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                                && it.valueParameters.isEmpty()
А зачем так разделять на две строчки? И давай кстати название функции выведем в константу

2022-04-06 17:27 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    if (sizeFunction != null) {
Тут намного лучше сделать `checkNotNull()` один раз а потом спокойно работать не нагружая код nesting-ами

2022-04-06 18:05 UTC, ArtyomKopan commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    if (sizeFunction != null) {
Типа так?
```
val sizeFunction = checkNotNull(clazz.functions.find {
                        it.name.toString() == SHALLOW_SIZE_FUNCTION_NAME && it.valueParameters.isEmpty()
                    })
```

2022-04-06 18:05 UTC, ArtyomKopan commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    if (sizeFunction != null) {
Нужно ли как-то обрабатывать исключение, которое в случае чего бросает checkNotNull?

2022-04-06 18:55 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    if (sizeFunction != null) {
Лучше сделать `checkNotNull(sizeFunction)`

2022-04-06 18:56 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    if (sizeFunction != null) {
Думаю не надо обрабатывать. Напиши главное адекватный `message`

2022-04-19 07:37 UTC, nbirillo approved these changes
Лучше ведь поздно, чем никогда :)

2022-04-19 19:44 UTC, merged